---
- name: "service install"
  apt:
      name: chrony
      state: present
      install_recommends: no


- name: "service start"
  service:
      name: "{{ time_synchronization_service[ansible_os_family] }}"
      state: started
      enabled: yes
