---
- name: "service install"
  package:
      name: chrony
      state: present


- name: "service start"
  service:
      name: "{{ time_synchronization_service[ansible_os_family] }}"
      state: started
      enabled: yes
